In [1]:
# !pip install google-play-scraper

In [2]:
from google_play_scraper import app, Sort, reviews_all
import pandas as pd
import numpy as np

In [3]:
id_reviews = reviews_all(
    'com.roblox.client',
    sleep_milliseconds=0, # defaults to 0
    lang = 'id',
    country = 'id',
    sort = Sort.MOST_RELEVANT, # defaults to Sort.MOST_RELEVANT
    count = 15000
)

In [4]:
print("Jumlah Data:", len(id_reviews))

Jumlah Data: 72000

In [5]:
df = pd.DataFrame(id_reviews)
df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,80b7b59c-021c-4686-b489-c83f91aa4eff,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Semenjak viral server Mount dan banyak yg join...,1,119,2.694.983,2025-10-14 13:55:53,None,None,2.694.983
1,f8ea2835-6a40-4ac7-8ee8-5f54ea4df454,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"game nya bagus, dan seru.. cuma bisa minta tol...",4,4696,2.693.960,2025-10-10 20:55:15,None,None,2.693.960
2,ec58b3f1-70a2-4aa6-bba7-cff7ae2b9ec6,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,minnnn tolong kerjasamanya minnn 🤗🤗 sejauh ini...,3,32,2.693.960,2025-10-15 21:27:16,None,None,2.693.960
3,dedfd44d-faa6-4f34-8707-d68414200c28,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Udah dari lama denger tentang roblox, tapi juj...",5,744,2.694.983,2025-10-15 16:55:31,None,None,2.694.983
4,155a7030-22b4-4015-a6ce-b277c06a7e81,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"sebenernya Udah cukup memuaskan, tapi ada 1 ha...",3,22,2.694.983,2025-10-14 10:51:22,None,None,2.694.983

In [6]:
df.tail()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
71995,17ac42d1-66a1-466b-8e1b-3ba05560e341,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,buat kalian yg gatau cara ngatasi kamera gamau...,5,0,2.617.654,2024-04-01 21:30:55,None,None,2.617.654
71996,0fb26c10-8cad-40cd-b58c-5e44a77964b4,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,dari grafik bagus dan gameplay bagus tapi ada ...,4,0,2.437.406827,2020-07-01 21:46:26,None,None,2.437.406827
71997,6e7cf4f3-98fc-4f5d-85a6-99b693a2322b,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Roblox nya bagus tapi ada bug yaitu bug kamera...,5,3,2.605.660,2023-12-13 18:32:46,None,None,2.605.660
71998,5826e294-a8fb-4f58-88a8-5ddf5648d883,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Maling bagus soalnya kalau masuk ke map block ...,5,2,2.545.432,2022-09-24 13:13:20,None,None,2.545.432
71999,a4ae810a-a60c-479b-a966-42d0028dc5d1,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Game ini sangat menyenangkan Walaupun Agak Nge...,5,0,2.648.781,2025-05-06 11:51:34,None,None,2.648.781

In [7]:
df.to_csv('data_review_roblox.csv', index=False)
print("Data saved to 'data_review_roblox.csv'")

Data saved to 'data_review_roblox.csv'